import Head from "next/head";

const Meta = ({ title }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      {/* <link
        href="https://fonts.cdnfonts.com/css/futura-md-bt"
        rel="stylesheet"
      /> */}
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
Meta.defaultProps = {
  title: "Where in the world ?",
};

export default Meta;
